ARRAY--INDEXING 

1.Fetching the value

In [3]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr[0]

array([1, 2, 3])

In [6]:
arr[2]

array([7, 8, 9])

In [10]:
row, column = arr.shape
row, column

(3, 3)

In [12]:
for i in range(0, row):
 print(arr[0][i])
 print(arr[2][i])

1
7
2
8
3
9


In [13]:
arr[1, 0]

np.int64(4)

In [14]:
arr_new = np.array([4,5,6])
arr_new

array([4, 5, 6])

In [15]:
arr_new[-1]

np.int64(6)

In [ ]:
arr[-2] # 2 nd row

array([4, 5, 6])

In [17]:
arr[1,1] = 55
arr

array([[ 1,  2,  3],
       [ 4, 55,  6],
       [ 7,  8,  9]])

In [ ]:
# change a row
arr[1] = [2,3,56]
arr


array([[ 1,  2,  3],
       [ 2,  3, 56],
       [ 7,  8,  9]])

In [21]:
arr[0] = 2
arr

array([[ 2,  2,  2],
       [ 2,  3, 56],
       [ 7,  8,  9]])

In [25]:
arr[0] += 3
arr

array([[ 6,  6,  6],
       [ 2,  3, 56],
       [ 7,  8,  9]])