RANDOM GENERATOR IN NUMPY

In [2]:
import numpy as np
from numpy.random import Generator as gen 
from numpy.random import PCG64 as pcg

In [6]:
arr_rg = gen(pcg())
arr_rg

Generator(PCG64) at 0x7A56C7B790E0

we above get some values which is generator type.
It generates a random value it depends upon which type of distribution value we need normal distribution, mean distribution , here we will use Normal distribution
arr_rg = gen(pcg())
arr_rg.normal(size = (5,5)) -> It will generate the matrix of 5 * 5  with random values. 

In [10]:
arr_rg = gen(pcg())
arr_rg.normal(size = (5,5))


array([[ 0.06152979, -0.14507844,  1.6509051 , -0.07940497, -0.29301609],
       [ 1.03034187, -1.51382463,  1.17773065,  0.74949214, -0.04258849],
       [-0.04418439,  0.91486368,  0.0369275 , -0.12384551, -0.39920681],
       [-0.62254952, -1.72359583,  0.0637654 ,  1.88733368,  0.66274723],
       [ 1.06772115,  0.57440659, -0.16175199,  0.16341579, -0.08689451]])

arr_rg = gen(pcg(seed = 101))-> make sure that same value is generated after each run .
arr_rg.normal(size = (5,5))

In [12]:
arr_rg = gen(pcg(seed = 101))
arr_rg.normal(size = (5,5))

array([[-0.7901525 , -2.03462548,  0.60330175,  0.74429453, -0.3096868 ],
       [ 0.36732137,  1.71039429,  1.06079784,  0.70763902,  0.68774939],
       [-0.86356745,  0.96401673, -1.64846282, -0.33209181, -0.43729384],
       [-1.72851871, -0.11033889,  1.64345508, -0.34012734, -1.20760334],
       [-0.09105372,  0.85392432,  0.19321812, -0.00266572, -1.40922226]])

TO generate INTEGER  value as random value we must give the range from low to high along with size.
SEED may/ may not used as per use.

In [13]:
arr_rg.integers(low = 1, high=2000, size=(4,4))

array([[1787, 1636,  945, 1334],
       [1339,  941,  839, 1939],
       [ 909, 1680,  796,  490],
       [1716, 1135, 1165, 1911]])

In [ ]:
arr_rg= gen(pcg (seed = 1000))
arr_rg.random(size= (4,4))
# random follow bell curve values

array([[0.52138574, 0.60384185, 0.4709418 , 0.20324794],
       [0.52875903, 0.19103628, 0.2815456 , 0.75368155],
       [0.55167178, 0.86372208, 0.80537222, 0.24837266],
       [0.18985741, 0.98399558, 0.66999717, 0.28038283]])