Creating A Numpy Array

In [2]:
import numpy as  np
arr = np.array([1,2,3]) # 1-D array
print(arr)

[1 2 3]


In [4]:
arr2 = np.array([[1,2,3],[2,3,4]])
print(arr2)

[[1 2 3]
 [2 3 4]]


In [5]:
arr2.dtype

dtype('int64')

Shape

In [6]:
arr2.shape

(2, 3)

Size

In [7]:
arr2.size

6

Dimension

In [8]:
arr2.ndim

2

Empty array with all Zero WITH 3 * 3 

In [ ]:
zeros = np.zeros((3,3))
zeros
# zeros.dtype float hota hai

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
zeros1 = np.zeros((3,3), dtype = int)
zeros1


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
ones =np.ones((4,4), dtype=str) # as string
ones

array([['1', '1', '1', '1'],
       ['1', '1', '1', '1'],
       ['1', '1', '1', '1'],
       ['1', '1', '1', '1']], dtype='<U1')

When we want to use a range of values in array use "ARRANGE"

In [21]:
arr_range = np.arange(10)
arr_range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

if we want 10 numbers betwenn 1 to 5 inclusive with equal distribution "linspace(1,5, 10) "

In [24]:
arr2_arange = np.linspace(1,5, 10) 
arr2_arange

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])