 SLICING IN NUMPY

In [3]:
import numpy as np
arr = np.array([[1,2,3],[3,4,5],[6,7,8]])
arr

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
arr[:]

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
arr[:1]

array([[1, 2, 3]])

In [6]:
arr[0:1]

array([[1, 2, 3]])

In [7]:
arr[2:]

array([[6, 7, 8]])

arr[0:1,1:] "0: 1" means row && "1:" from row before this give from 1 to end

In [8]:
arr[0:1,1:]

array([[2, 3]])

In [9]:
arr_max = np.array([[1,2,3,4,4,5],[3,5,3,2,4,5],[7,5,6,7,5,0,],[2,6,9,0,6,4]])
arr_max

array([[1, 2, 3, 4, 4, 5],
       [3, 5, 3, 2, 4, 5],
       [7, 5, 6, 7, 5, 0],
       [2, 6, 9, 0, 6, 4]])

In [10]:
arr_max[:1,1:5]

array([[2, 3, 4, 4]])

In [11]:
arr_max[:2, :5]

array([[1, 2, 3, 4, 4],
       [3, 5, 3, 2, 4]])

we can change ni=umbers of steps after which elements is printed by defalut it is 1 and not written while writting the code
arr_max[0:4:2, :5]

will print 1 and 3rd row from 0 to 4 th index number

In [12]:
arr_max[0:4:2, :5]

array([[1, 2, 3, 4, 4],
       [7, 5, 6, 7, 5]])

arr_max[1:4:2, 0:6:2] will print 2 nd 7 4 rth row 
and in each row it will print 0,2,4 index numbers elemnets

In [13]:
arr_max[1:4:2, 0:6:2] 

array([[3, 3, 4],
       [2, 9, 6]])