BROADCASTING IN NUMPY

In [2]:
import numpy as np
ar1 = np.array([1,2,3])
print(ar1)
ar2 = np.array([5,6,7])
print(ar2)

[1 2 3]
[5 6 7]


In [3]:
ar2 + ar1

array([ 6,  8, 10])

Addition is very simple as dimention is same .

Adiiona single element array 
ar1 = [1,2,3]
ar1 + 4
ar1 = [5,6,7] temporarely chaned

In [5]:
ar1 + 4


array([5, 6, 7])

Adding two different dimensionaed array

In [6]:
arr = np.array([2,3,4])
print(arr)
arrr2 = np.array([[2],[3],[4]])
print(arrr2)

[2 3 4]
[[2]
 [3]
 [4]]


In [7]:
arr + arrr2

array([[4, 5, 6],
       [5, 6, 7],
       [6, 7, 8]])

Adding two different array (dimensioned diffrently) is called bradcasting.

Behind the scenes

 arr = [1,2,3] becomes [[1,2,3], a row is copied
                        [1,2,3],
                        [1,2,3]]

And 
arr2 = [[2],
[3],
[4]] become, a column is copied 
                            [[2,2,2]
                            [3,3,3],
                            [4,4,4]]
                
    [[1,2,3],          [[2,2,2],         
    [1,2,3],    +        [3,3,3],
    [1,2,3]]              [4,4,4],]

In [9]:
arr3 = np.array([1,2,3]) # shape 1 *  3
arr4 = np.array([1,2,3,4]) # shape 1*4
arr3 + arr4

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

Here dimension were not same but why error?
Bcs there is some rule for bradcasting 
1. for broadcasting the array shape from right should be equal 
