NUMPY ARRAY MANIPULATION

1. Reshaping

In [5]:
import numpy as np
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
reshaped = arr.reshape(2,6) # 2 positional argument
reshaped

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

2. Flattening the array

In [19]:
flattened = reshaped.flatten()
flattened[0] = 99
flattened


array([99,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
reshaped

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

3. Raveling 
(a->Why ravel not flat as flat creates a new reference to copy of data to new memory, but in ravel it is showing same memory refrence, it showing(view) us only that it is single dimension so that we can to some 1- d operations 
b-> Flat also utilize more memory and thus less time efficient)
c-> Even ravel creates a copy of array if array is not contigious memeory location.

In [ ]:
raveled = reshaped.ravel()
raveled[0] = 99
raveled



array([[99,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [24]:
reshaped

array([[99,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])